

name: Run Trading Script Dhtohlcv and dht3 only

on:
  schedule:
    - cron: '0 12 * * 1-5'   # Example: 5:30 PM IST (adjust as needed)
  workflow_dispatch:        # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script dhtohlcv
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DHAN_API_KEY: ${{ secrets.DHAN_API_KEY }}
          DHAN_CHAT_ID: ${{ secrets.DHAN_CHAT_ID }}
         run: |
          python Dhtohlcv.py  
          
      - name: Commit updated Excel file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ohlcv_output_today11.xlsx
          git diff --cached --quiet || git commit -m "Auto update OHLCV Excel"
          git push          

      - name: Run script dht3
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DHAN_API_KEY: ${{ secrets.DHAN_API_KEY }}
          DHAN_CHAT_ID: ${{ secrets.DHAN_CHAT_ID }}

        run: |
          python Dht3.py
